version: '3.7'
services:
  mongodb:
    image: aywdocker/mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb

volumes:
  mongodata:
  mongoconfig:

